Update protobuf dependency to 3.22.3
Protobuf 3.22 made some changes such that projects that compile with protobuf 3.22 have a compiled version of `Struct.Builder` that is missing a method. The exact error message is the following:

```
java.lang.NoSuchMethodError: 'com.google.protobuf.Struct$Builder com.google.protobuf.Struct$Builder.addRepeatedField(com.google.protobuf.Descriptors$FieldDescriptor, java.lang.Object)'

	at com.hubspot.jackson.datatype.protobuf.builtin.deserializers.StructDeserializer.populate(StructDeserializer.java:28)
```

This change bumps protobuf version to 3.22.3, which causes the reference to addRepeatedField to be correct.